// schema — composable, complement-carrying lenses between plain-POJO schema
// versions. See lens.ts for the kit and the design rationale.

export {
  addField,
  addV,
  each,
  eachBy,
  type FieldMap,
  headField,
  headV,
  inField,
  into,
  mapElems,
  mapField,
  nestFields,
  nestV,
  type Obj,
  type OLens,
  onField,
  pipe,
  recurse,
  removeField,
  removeV,
  renameField,
  renameV,
  type SplitSpec,
  type Step,
  seq,
  splitField,
  splitV,
  toStep,
  type VLens,
  wrapField,
  wrapV,
} from "./lens";
